services:
  postgres:
    image: postgres:latest
    container_name: laravel-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tdd
    ports:
      - "5432:5432"