version: '3'

services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"

  postgres:
    image: postgres:latest
    container_name: laravel-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: consultai
    ports:
      - "5432:5432"