apiVersion: v1
kind: Service
metadata:
  name: consultai-laravel
spec:
  type: NodePort
  selector:
    app: consultai-laravel
  ports:
  - port: 8000
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultai-laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultai-laravel
  template:
    metadata:
      labels:
        app: consultai-laravel
    spec:
      containers:
      - name: consultai-laravel
        image: clinica-consultai_laravel-docker
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 80




