apiVersion: v1
kind: Service
metadata:
  name: consultai-postgres
spec:
  selector:
    app: consultai-postgres
  ports:
  - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultai-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultai-postgres
  template:
    metadata:
      labels:
        app: consultai-postgres
    spec:
      containers:
      - name: consultai-postgres
        image: postgres
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config

    
